// default package
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private int id;
	private String addressLine;
	private String city;
	private String country;

	public Address() {
	}

	public Address(int id, String addressLine) {
		this.id = id;
		this.addressLine = addressLine;
	}

	public Address(int id, String addressLine, String city, String country) {
		this.id = id;
		this.addressLine = addressLine;
		this.city = city;
		this.country = country;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAddressLine() {
		return this.addressLine;
	}

	public void setAddressLine(String addressLine) {
		this.addressLine = addressLine;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
