// default package
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * Gametyping generated by hbm2java
 */
public class Gametyping implements java.io.Serializable {

	private GametypingId id;

	public Gametyping() {
	}

	public Gametyping(GametypingId id) {
		this.id = id;
	}

	public GametypingId getId() {
		return this.id;
	}

	public void setId(GametypingId id) {
		this.id = id;
	}

}
