// default package
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * Orderline generated by hbm2java
 */
public class Orderline implements java.io.Serializable {

	private OrderlineId id;

	public Orderline() {
	}

	public Orderline(OrderlineId id) {
		this.id = id;
	}

	public OrderlineId getId() {
		return this.id;
	}

	public void setId(OrderlineId id) {
		this.id = id;
	}

}
