package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private int id;
	private String address_line;
	private String city;
	private String country;
	private int owner;

	public Address() {
	}

	public Address(int id, String address_line) {
		this.id = id;
		this.address_line = address_line;
	}

	public Address(int id, String address_line, String city, String country, int owner) {
		this.id = id;
		this.address_line = address_line;
		this.city = city;
		this.country = country;
		this.owner = owner;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAddressLine() {
		return this.address_line;
	}

	public void setAddressLine(String addressLine) {
		this.address_line = addressLine;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
