package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * ConsolebelongingId generated by hbm2java
 */
public class ConsolebelongingId implements java.io.Serializable {

	private int videogame;
	private String console;

	public ConsolebelongingId() {
	}

	public ConsolebelongingId(int videogame, String console) {
		this.videogame = videogame;
		this.console = console;
	}

	public int getVideogame() {
		return this.videogame;
	}

	public void setVideogame(int videogame) {
		this.videogame = videogame;
	}

	public String getConsole() {
		return this.console;
	}

	public void setConsole(String console) {
		this.console = console;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConsolebelongingId))
			return false;
		ConsolebelongingId castOther = (ConsolebelongingId) other;

		return (this.getVideogame() == castOther.getVideogame())
				&& ((this.getConsole() == castOther.getConsole()) || (this.getConsole() != null
						&& castOther.getConsole() != null && this.getConsole().equals(castOther.getConsole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVideogame();
		result = 37 * result + (getConsole() == null ? 0 : this.getConsole().hashCode());
		return result;
	}

}
