package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * Gametype generated by hbm2java
 */
public class Gametype implements java.io.Serializable {

	private String name;

	public Gametype() {
	}

	public Gametype(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
