package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * GametypingId generated by hbm2java
 */
public class GametypingId implements java.io.Serializable {

	private int videogame;
	private String gametype;

	public GametypingId() {
	}

	public GametypingId(int videogame, String gametype) {
		this.videogame = videogame;
		this.gametype = gametype;
	}

	public int getVideogame() {
		return this.videogame;
	}

	public void setVideogame(int videogame) {
		this.videogame = videogame;
	}

	public String getGametype() {
		return this.gametype;
	}

	public void setGametype(String gametype) {
		this.gametype = gametype;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GametypingId))
			return false;
		GametypingId castOther = (GametypingId) other;

		return (this.getVideogame() == castOther.getVideogame())
				&& ((this.getGametype() == castOther.getGametype()) || (this.getGametype() != null
						&& castOther.getGametype() != null && this.getGametype().equals(castOther.getGametype())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVideogame();
		result = 37 * result + (getGametype() == null ? 0 : this.getGametype().hashCode());
		return result;
	}

}
