package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * OrderlineId generated by hbm2java
 */
public class Orderline implements java.io.Serializable {

	private int orderId;
	private Videogame videogame;
	private Integer quantity;

	public Orderline() {
	}


	public Orderline( Videogame videogame, Integer quantity) {
		this.videogame = videogame;
		this.quantity = quantity;
	}

	public Orderline(int orderId, Videogame videogame, Integer quantity) {
		this.orderId = orderId;
		this.videogame = videogame;
		this.quantity = quantity;
	}


	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public Videogame getVideogame() {
		return this.videogame;
	}

	public void setVideogame(Videogame videogame) {
		this.videogame = videogame;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
