package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int id;
	private Date date;
	private Float total;
	private int client;
	private int address;

	public Orders() {
	}

	public Orders(int id, int client, int address) {
		this.id = id;
		this.client = client;
		this.address = address;
	}

	public Orders(int id, Date date, Float total, int client, int address) {
		this.id = id;
		this.date = date;
		this.total = total;
		this.client = client;
		this.address = address;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public int getClient() {
		return this.client;
	}

	public void setClient(int client) {
		this.client = client;
	}

	public int getAddress() {
		return this.address;
	}

	public void setAddress(int address) {
		this.address = address;
	}

}
