package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

import java.sql.Date;
import java.util.List;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int id;
	private Date date;
	private Float total;
	private Client client;
	private Address address;
	private List<Orderline> lines;
	
	public Orders() {
	}

	public Orders(int id, Client client, Address address) {
		this.id = id;
		this.setClient(client);
		this.setAddress(address);
	}

	public Orders(int id, Date date, Float total, Client client, Address address) {
		this.id = id;
		this.date = date;
		this.total = total;
		this.setClient(client);
		this.setAddress(address);
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}


	public List<Orderline> getLines() {
		return lines;
	}

	public void setLines(List<Orderline> lines) {
		this.lines = lines;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

}
