package beans;
// Generated 4 avr. 2017 18:57:40 by Hibernate Tools 5.1.0.Alpha1

/**
 * Videogame generated by hbm2java
 */
public class Videogame implements java.io.Serializable {

	private int id;
	private String title;
	private Float price;
	private Console console; // optional and used only to wrap whole res from JOIN in one videogame object
	private Gametype gameType;  // optional and used only to wrap whole res from JOIN in one videogame object
	
	public Videogame() {
	}

	public Videogame(int id) {
		this.id = id;
	}

	public Videogame(int id, String title, Float price) {
		this.id = id;
		this.title = title;
		this.price = price;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Console getConsole() {
		return this.console;
	}

	public void setConsole(Console console) {
		this.console = console;
	}

	public Gametype getGametype() {
		return this.gameType;
	}

	public void setGametype(Gametype gameType) {
		this.gameType = gameType;
	}
}
